<?xml version="1.0"?>
<package format="3">
  <name>krthumanrobot_urdf</name>
  <version>0.1.0</version>
  <description>Whole robot description and MoveIt collision model.</description>
  <maintainer email="r465755956@gmail.com">create</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
