<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>krt_human_robot</name>
  <version>0.1.0</version>
  <description>KrtHumanRobot core behavior tree entry point</description>
  <maintainer email="r465755956@gmail.com">create</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>ament_index_python</depend>
  <depend>voice_interfaces</depend>
  <depend>krt_task_interfaces</depend>
  <depend>agx_action_group_interfaces</depend>
  <depend>hands_control_interfaces</depend>
  <depend>lifecycle_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>

  <exec_depend>hand_camera_driver</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>voice_assistant</exec_depend>
  <exec_depend>ranger_nav</exec_depend>
  <exec_depend>krt_task</exec_depend>
  <exec_depend>agx_action_group_runner</exec_depend>
  <exec_depend>agx_arm_ctrl</exec_depend>
  <exec_depend>pcd2pgm</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-loguru</exec_depend>
  <exec_depend>py_trees</exec_depend>
  <exec_depend>py_trees_ros</exec_depend>
  <exec_depend>py_trees_ros_interfaces</exec_depend>
  <exec_depend>hands_control</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
