<?xml version="1.0"?>
<package format="3">
  <name>krthumanrobot_moveit_config</name>
  <version>0.1.0</version>
  <description>MoveIt 2 configuration for KRT dual arm robot.</description>
  <maintainer email="r465755956@gmail.com">create</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>krthumanrobot_urdf</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_ros_visualization</exec_depend>
  <exec_depend>moveit_planners_ompl</exec_depend>
  <exec_depend>moveit_kinematics</exec_depend>
  <exec_depend>moveit_simple_controller_manager</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>agx_arm_ctrl</exec_depend>
  <exec_depend>agx_arm_moveit</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>moveit_core</test_depend>
  <test_depend>tf2_ros</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
